// ================= SAFE UI LANGUAGE SWITCHER =================
// Business logic never depends on the selected language. Only presentation
// strings are translated, which prevents the old ENG/CN/ID regression where
// changing language could interfere with application logic.
const LANG_KEY = '3475_ui_language';
// Language order in the UI: ENG / ID / CN. Business logic is language-neutral.
const translations = {
  en: {
    statusAccepted:'Accepted', statusRejected:'Rejected', statusWaiting:'Waiting', statusUpdated:'Updated', detailPrefix:'Detail', statePrefix:'State', maxSlotsUpdated:'Maximum slots updated to {max}', nativeUpdateTitle:'Transfer Application Update', nativeUpdateBody:'Application #{id} is now {status}.', nativeAcceptedTitle:'Application Accepted 🎉', nativeAcceptedBody:'{nickname} has been accepted! Welcome to the state.', nativeRejectedTitle:'Application Rejected', nativeRejectedBody:'{nickname} was rejected. Check the portal for details.', yourApplication:'Your application', specialNotesSaved:'Special Notes saved to server!', specialNotesSaveFailed:'Error saving special notes', stateInfoSaved:'State profile information updated live!', stateInfoSaveFailed:'Failed saving state info', infoFieldsRequired:'All info fields must be filled!', infoSaved:'Information saved to 3475 Server', infoSaveFailed:'Database failed saving information', invalidSlots:'Invalid slots number!', maxSlotsUpdateFailed:'Failed to update max slots on server', adminNoteSaved:'Admin note saved successfully!', adminNoteSaveFailed:'Error saving note', recordDeleted:'Record deleted successfully.', deleteFailed:'Delete failed', adminPasswordRequired:'Please enter the admin password!', resetVerificationFailed:'Reset canceled. Verification security check failed.', confirmDelete:'Delete {name} permanently?\n\nThis cannot be undone.', confirmReset:'⚠️ WARNING\n\nYou are about to permanently delete {count} transfer application(s).\n\nThis action cannot be undone.', verifying:'Verifying...', allRecordsCleared:'All transfer records have been cleared!', resetFailed:'Reset failed', acceptVerb:'accept', rejectVerb:'reject', loginFieldsRequired:'Please enter both username and password!', presidentOnly:'This page is for the President account only.', loginFailed:'Login failed: incorrect username or password', welcomePresident:'Welcome back, President!', presidentLogout:'President Logout', noDataExport:'No data to export', noTrackedApplications:'No tracked applications on this device yet. Submit the form with “Get Notification?” checked, or recover an application above.', loadingStatus:'Loading status…', recordNotFound:'Record not found' ,
    nativeUpdateTitle:'Transfer Application Update', nativeUpdateBody:'Application #{id} is now {status}.', nativeAcceptedTitle:'Application Accepted 🎉', nativeAcceptedBody:'{nickname} has been accepted! Welcome to the state.', nativeRejectedTitle:'Application Rejected', nativeRejectedBody:'{nickname} was rejected. Check the portal for details.', yourApplication:'Your application', logout:'Logout', presidentLoginShort:'President Login', noApplications:'No applications found', accept:'Accept', reject:'Reject', delete:'Delete', details:'Details', copyId:'Copy ID', pageTitle:'Player Transfer Registration', portalTitle:'3475 - Transfer Portal', portalSubtitle:'Apply your data to immigrate state',
    presidentManager:'President/State Manager:', alliance:'Aliansi:', gameIdShort:'ID:', save:'💾 Save', specialNotes:'📝 Special Notes', presidentMode:'● President Mode',
    transferForm:'Transfer Form', transferSubtitle:'Enter your transfer details once. You can check the status below in real time.', aboutState:'About Our State', aboutStateTitle:'ℹ️ About Our State', myApplicationStatus:'🔔 My Application Status',
    total:'Total', accepted:'Accepted', left:'Left', registrationClosed:'⚠️ REGISTRATION CLOSED', quotaFull:'The accepted quota is currently full.',
    transferFromState:'Transfer From State', fromState:'From State', nickname:'Nickname', gameId:'Game ID', desiredAlliance:'Desired Alliance', furnaceLevel:'Furnace Level', power:'Power', heroPower:'Hero Power', totalHeroPower:'Total Hero Power', referrerOptional:'Referrer (Optional)', referrer:'Referrer',
    getNotification:'🔔 Get Notification?', trackLive:"Track this application's status live on this device", submitApplication:'Submit Application', submitHint:'Your application will appear in the list immediately after submission.', viewApplicants:'View Applicants',
    applicantsList:'Applicants List', realtimeStatus:'Real-time application status', resetPhase:'⚠️ Reset Phase', exportCsv:'⇩ Export CSV', view:'View', action:'Action', from:'From', status:'Status', playerDetail:'Player Detail', adminNotes:'Admin Notes:', saveNote:'💾 Save Note',
    saveStateInfo:'💾 Save State Info', adminSpecialNotes:'📝 Admin Special Notes', specialNotesOnly:'Only President/State Manager can see and edit this field.', saveSpecialNotes:'💾 Save Special Notes', presidentLogin:'👑 President Login', username:'Username', password:'Password', login:'🔐 Login', confirmPhaseReset:'⚠️ Confirm Phase Reset', resetWarning:'This will permanently delete ALL transfer records. Enter the admin password to confirm.', adminPassword:'Admin Password', deleteAllRecords:'⚠️ Delete All Records',
    recoveryTitle:'🔐 Save Your Recovery Code', recoveryIntro:'Keep these two values safe. They are required to recover notifications on another device or after browser data is cleared.', applicationIdLabel:'Application ID', recoveryCodeLabel:'Recovery Code', copyRecovery:'📋 Copy Recovery Code', recoveryWarning:'Do not share this code publicly. Anyone with both values may be able to track this application.', recoverLabel:'Recover / Add Application', checkButton:'Check', recoverHelp:'Lost tracking on a new device or after clearing browser data? Enter the Application ID and Recovery Code saved after submission.',
    fillAllFields:'Please fill all input fields!', gameIdNumbers:'Game ID must contain numbers only!', invalidNumbers:'Please enter a valid, non-negative State and Furnace Level!', furnaceRange:'Furnace Level must be between 1 and 10!', submitSuccess:'Transfer application sent successfully!', submitError:'Error submitting', unauthorized:'Unauthorized action!', confirmStatus:'Are you sure you want to {action} this player transfer application?', quotaReached:'Cannot accept! Quota limit ({max}) has been reached.', applicationStatusSuccess:'Application {status} successfully!', statusUpdateFailed:'Failed to update status', notificationsBlocked:'Browser notifications are blocked. You can enable them in browser settings.', notificationsEnabled:'Browser notifications enabled.', notificationTracked:'🔔 Notifications enabled for Application #{id}', trackingInApp:'🔔 Application #{id} is being tracked with in-app alerts.', invalidApplicationId:'Please enter a valid numeric Application ID.', invalidRecoveryCode:'Please enter the 8-character Recovery Code.', recoveryFailed:'Application ID or Recovery Code is incorrect.', trackingRestored:'Application #{id} is now being tracked on this device.', furnaceTouchRequired:'Please set your Furnace Level by dragging the slider first!',
    statePlaceholder:'e.g. 3475', nicknamePlaceholder:'Enter nickname', gameIdPlaceholder:'Enter Game ID', alliancePlaceholder:'e.g. ARX/CAT/IDN/VNX/ZXC', yourPower:'Your Power', strongestHeroPower:'Strongest Hero Power', totalHeroPowerPlaceholder:'Total Hero Power', referrerPlaceholder:'Who referred you? (optional)', stateInfoPlaceholder:'Write about state rules, requirements, or profile here...', adminNotePlaceholder:'Add private note for this applicant...', usernamePlaceholder:'Username', passwordPlaceholder:'Password', adminPasswordPlaceholder:'Admin password', applicationIdPlaceholder:'Application ID', recoveryCodePlaceholder:'Recovery Code'
  },
  cn: {
    statusAccepted:'已接受', statusRejected:'已拒绝', statusWaiting:'等待中', statusUpdated:'已更新', detailPrefix:'详情', statePrefix:'州', maxSlotsUpdated:'最大名额已更新为 {max}', nativeUpdateTitle:'转州申请更新', nativeUpdateBody:'申请 #{id} 当前状态：{status}。', nativeAcceptedTitle:'申请已接受 🎉', nativeAcceptedBody:'{nickname} 已被接受！欢迎来到本州。', nativeRejectedTitle:'申请被拒绝', nativeRejectedBody:'{nickname} 的申请被拒绝，请查看门户获取详情。', yourApplication:'您的申请', specialNotesSaved:'特别备注已保存到服务器！', specialNotesSaveFailed:'保存特别备注失败', stateInfoSaved:'州资料已实时更新！', stateInfoSaveFailed:'保存州资料失败', infoFieldsRequired:'所有信息字段都必须填写！', infoSaved:'信息已保存到 3475 服务器', infoSaveFailed:'数据库保存信息失败', invalidSlots:'名额数量无效！', maxSlotsUpdateFailed:'更新服务器名额失败', adminNoteSaved:'管理员备注保存成功！', adminNoteSaveFailed:'保存备注失败', recordDeleted:'记录删除成功。', deleteFailed:'删除失败', adminPasswordRequired:'请输入管理员密码！', resetVerificationFailed:'重置已取消，验证安全检查失败。', confirmDelete:'确定永久删除 {name} 吗？\n\n此操作无法撤销。', confirmReset:'⚠️ 警告\n\n您即将永久删除 {count} 个转州申请。\n\n此操作无法撤销。', verifying:'验证中……', allRecordsCleared:'所有转州记录已清除！', resetFailed:'重置失败', acceptVerb:'接受', rejectVerb:'拒绝', loginFieldsRequired:'请输入用户名和密码！', presidentOnly:'此页面仅供州长账户使用。', signingIn:'登录中……', loginFailed:'登录失败：用户名或密码错误', welcomePresident:'欢迎回来，州长！', presidentLogout:'州长已退出登录', noDataExport:'没有可导出的数据', noTrackedApplications:'此设备暂无追踪中的申请。提交时勾选“获取通知”，或恢复一个申请。', loadingStatus:'正在加载状态……', recordNotFound:'找不到记录' ,
    nativeUpdateTitle:'转州申请更新', nativeUpdateBody:'申请 #{id} 当前状态：{status}。', nativeAcceptedTitle:'申请已接受 🎉', nativeAcceptedBody:'{nickname} 已被接受！欢迎来到本州。', nativeRejectedTitle:'申请被拒绝', nativeRejectedBody:'{nickname} 的申请被拒绝，请查看门户获取详情。', yourApplication:'您的申请', logout:'退出登录', presidentLoginShort:'州长登录', noApplications:'暂无申请', accept:'接受', reject:'拒绝', delete:'删除', details:'详情', copyId:'复制 ID', pageTitle:'玩家转州登记', portalTitle:'3475 - 转州门户', portalSubtitle:'填写您的资料以申请转州', presidentManager:'州长/州管理者：', alliance:'联盟：', gameIdShort:'ID：', save:'💾 保存', specialNotes:'📝 特别备注', presidentMode:'● 州长模式',
    transferForm:'转州申请表', transferSubtitle:'只需填写一次资料，您可以在下方实时查看申请状态。', aboutState:'州信息', aboutStateTitle:'ℹ️ 关于本州', myApplicationStatus:'🔔 我的申请状态', total:'总数', accepted:'已接受', left:'剩余', registrationClosed:'⚠️ 登记已关闭', quotaFull:'已接受名额已满。',
    transferFromState:'原州', fromState:'原州', nickname:'游戏昵称', gameId:'游戏 ID', desiredAlliance:'目标联盟', furnaceLevel:'熔炉等级', power:'战力', heroPower:'英雄战力', totalHeroPower:'英雄总战力', referrerOptional:'推荐人（可选）', referrer:'推荐人', getNotification:'🔔 获取通知？', trackLive:'在此设备上实时追踪申请状态', submitApplication:'提交申请', submitHint:'提交后，您的申请会立即显示在列表中。', viewApplicants:'查看申请人', applicantsList:'申请人列表', realtimeStatus:'实时申请状态', resetPhase:'⚠️ 重置阶段', exportCsv:'⇩ 导出 CSV', view:'查看', action:'操作', from:'来自', status:'状态', playerDetail:'玩家详情', adminNotes:'管理员备注：', saveNote:'💾 保存备注', saveStateInfo:'💾 保存州信息', adminSpecialNotes:'📝 管理员特别备注', specialNotesOnly:'只有州长/州管理者可以查看和编辑此字段。', saveSpecialNotes:'💾 保存特别备注', presidentLogin:'👑 州长登录', username:'用户名', password:'密码', login:'🔐 登录', confirmPhaseReset:'⚠️ 确认重置阶段', resetWarning:'此操作将永久删除所有转州记录。请输入管理员密码确认。', adminPassword:'管理员密码', deleteAllRecords:'⚠️ 删除所有记录',
    recoveryTitle:'🔐 保存您的恢复码', recoveryIntro:'请妥善保存以下两项信息。更换设备或清除浏览器数据后，需要它们来恢复通知追踪。', applicationIdLabel:'申请 ID', recoveryCodeLabel:'恢复码', copyRecovery:'📋 复制恢复码', recoveryWarning:'请勿公开分享此恢复码。拥有这两项信息的人可能可以追踪此申请。', recoverLabel:'恢复 / 添加申请', checkButton:'检查', recoverHelp:'如果更换设备或清除了浏览器数据，请输入提交申请后保存的申请 ID 和恢复码。',
    fillAllFields:'请填写所有输入项！', gameIdNumbers:'游戏 ID 只能包含数字！', invalidNumbers:'请为 State 和熔炉等级输入有效的非负数字。', furnaceRange:'熔炉等级必须在 1 到 10 之间！', submitSuccess:'转州申请提交成功！', submitError:'提交错误', unauthorized:'无权执行此操作！', confirmStatus:'确定要{action}此玩家的转州申请吗？', quotaReached:'无法接受！名额上限（{max}）已达到。', applicationStatusSuccess:'申请{status}成功！', statusUpdateFailed:'更新状态失败', notificationsBlocked:'浏览器通知已被阻止。您可以在浏览器设置中启用。', notificationsEnabled:'浏览器通知已启用。', notificationTracked:'🔔 已启用申请 #{id} 的通知', trackingInApp:'🔔 正在通过页面内通知追踪申请 #{id}。', invalidApplicationId:'请输入有效的申请 ID。', invalidRecoveryCode:'请输入 8 位恢复码。', recoveryFailed:'申请 ID 或恢复码不正确。', trackingRestored:'申请 #{id} 已在此设备恢复追踪。', furnaceTouchRequired:'请先拖动滑块设置熔炉等级！',
    statePlaceholder:'例如 3475', nicknamePlaceholder:'输入昵称', gameIdPlaceholder:'输入游戏 ID', alliancePlaceholder:'例如 ARX/CAT/IDN/VNX/ZXC', yourPower:'您的战力', strongestHeroPower:'最强英雄战力', totalHeroPowerPlaceholder:'英雄总战力', referrerPlaceholder:'谁推荐了您？（可选）', stateInfoPlaceholder:'填写州规则、要求或简介……', adminNotePlaceholder:'为此申请人添加私密备注……', usernamePlaceholder:'用户名', passwordPlaceholder:'密码', adminPasswordPlaceholder:'管理员密码', applicationIdPlaceholder:'申请 ID', recoveryCodePlaceholder:'恢复码'
  },
  id: {
    statusAccepted:'Diterima', statusRejected:'Ditolak', statusWaiting:'Menunggu', statusUpdated:'Diperbarui', detailPrefix:'Detail', statePrefix:'State', maxSlotsUpdated:'Maksimal slot diperbarui menjadi {max}', nativeUpdateTitle:'Pembaruan Aplikasi Transfer', nativeUpdateBody:'Aplikasi #{id} sekarang berstatus {status}.', nativeAcceptedTitle:'Aplikasi Diterima 🎉', nativeAcceptedBody:'{nickname} telah diterima! Selamat datang di state.', nativeRejectedTitle:'Aplikasi Ditolak', nativeRejectedBody:'{nickname} ditolak. Silakan cek portal untuk detailnya.', yourApplication:'Aplikasi Anda', specialNotesSaved:'Catatan Khusus berhasil disimpan ke server!', specialNotesSaveFailed:'Gagal menyimpan catatan khusus', stateInfoSaved:'Info profil state berhasil diperbarui secara real-time!', stateInfoSaveFailed:'Gagal menyimpan info state', infoFieldsRequired:'Semua kolom informasi harus diisi!', infoSaved:'Informasi berhasil disimpan ke Server 3475', infoSaveFailed:'Database gagal menyimpan informasi', invalidSlots:'Jumlah slot tidak valid!', maxSlotsUpdateFailed:'Gagal memperbarui slot di server', adminNoteSaved:'Catatan admin berhasil disimpan!', adminNoteSaveFailed:'Gagal menyimpan catatan', recordDeleted:'Data berhasil dihapus.', deleteFailed:'Gagal menghapus data', adminPasswordRequired:'Masukkan password admin!', resetVerificationFailed:'Reset dibatalkan. Verifikasi keamanan gagal.', confirmDelete:'Hapus {name} secara permanen?\n\nTindakan ini tidak dapat dibatalkan.', confirmReset:'⚠️ PERINGATAN\n\nAnda akan menghapus permanen {count} aplikasi transfer.\n\nTindakan ini tidak dapat dibatalkan.', verifying:'Memverifikasi...', allRecordsCleared:'Semua data transfer telah dihapus!', resetFailed:'Reset gagal', acceptVerb:'menerima', rejectVerb:'menolak', loginFieldsRequired:'Masukkan username dan password!', presidentOnly:'Halaman ini hanya untuk akun Presiden.', signingIn:'Sedang login...', loginFailed:'Login gagal: username atau password salah', welcomePresident:'Selamat datang kembali, Presiden!', presidentLogout:'Presiden Logout', noDataExport:'Tidak ada data untuk diekspor', noTrackedApplications:'Belum ada aplikasi yang dilacak di perangkat ini. Centang “Dapatkan Notifikasi” saat submit atau pulihkan aplikasi.', loadingStatus:'Memuat status…', recordNotFound:'Data tidak ditemukan' ,
    nativeUpdateTitle:'Pembaruan Aplikasi Transfer', nativeUpdateBody:'Aplikasi #{id} sekarang berstatus {status}.', nativeAcceptedTitle:'Aplikasi Diterima 🎉', nativeAcceptedBody:'{nickname} telah diterima! Selamat datang di state.', nativeRejectedTitle:'Aplikasi Ditolak', nativeRejectedBody:'{nickname} ditolak. Silakan cek portal untuk detailnya.', yourApplication:'Aplikasi Anda', logout:'Logout', presidentLoginShort:'Login Presiden', noApplications:'Tidak ada aplikasi', accept:'Terima', reject:'Tolak', delete:'Hapus', details:'Detail', copyId:'Salin ID', pageTitle:'Pendaftaran Transfer Pemain', portalTitle:'Portal Transfer 3475', portalSubtitle:'Isi data Anda untuk mengajukan pindah state', presidentManager:'Presiden/Manajer State:', alliance:'Aliansi:', gameIdShort:'ID:', save:'💾 Simpan', specialNotes:'📝 Catatan Khusus', presidentMode:'● Mode Presiden',
    transferForm:'Form Transfer', transferSubtitle:'Isi data transfer Anda sekali. Status dapat dipantau secara real-time di bawah.', aboutState:'Tentang State', aboutStateTitle:'ℹ️ Tentang State Kami', myApplicationStatus:'🔔 Status Aplikasi Saya', total:'Total', accepted:'Diterima', left:'Tersisa', registrationClosed:'⚠️ PENDAFTARAN DITUTUP', quotaFull:'Kuota yang diterima saat ini sudah penuh.',
    transferFromState:'State Asal', fromState:'Dari State', nickname:'Nickname Dalam Game', gameId:'Game ID', desiredAlliance:'Aliansi Tujuan', furnaceLevel:'Level Tungku', power:'Power', heroPower:'Hero Power', totalHeroPower:'Total Hero Power', referrerOptional:'Yang Mengundang (Opsional)', referrer:'Yang Mengundang', getNotification:'🔔 Dapatkan Notifikasi?', trackLive:'Pantau status aplikasi ini secara real-time di perangkat ini', submitApplication:'Kirim Aplikasi', submitHint:'Aplikasi Anda akan langsung muncul di daftar setelah dikirim.', viewApplicants:'Lihat Pendaftar', applicantsList:'Daftar Pendaftar', realtimeStatus:'Status aplikasi real-time', resetPhase:'⚠️ Reset Phase', exportCsv:'⇩ Export CSV', view:'Lihat', action:'Aksi', from:'Dari', status:'Status', playerDetail:'Detail Pemain', adminNotes:'Catatan Admin:', saveNote:'💾 Simpan Catatan', saveStateInfo:'💾 Simpan Info State', adminSpecialNotes:'📝 Catatan Khusus Admin', specialNotesOnly:'Hanya Presiden/Manajer State yang dapat melihat dan mengedit bagian ini.', saveSpecialNotes:'💾 Simpan Catatan Khusus', presidentLogin:'👑 Login Presiden', username:'Username', password:'Password', login:'🔐 Login', confirmPhaseReset:'⚠️ Konfirmasi Reset Phase', resetWarning:'Tindakan ini akan menghapus PERMANEN semua data transfer. Masukkan password admin untuk melanjutkan.', adminPassword:'Password Admin', deleteAllRecords:'⚠️ Hapus Semua Data',
    recoveryTitle:'🔐 Simpan Recovery Code Anda', recoveryIntro:'Simpan kedua informasi ini dengan aman. Keduanya diperlukan untuk memulihkan notifikasi di perangkat lain atau setelah data browser dihapus.', applicationIdLabel:'Application ID', recoveryCodeLabel:'Recovery Code', copyRecovery:'📋 Salin Recovery Code', recoveryWarning:'Jangan bagikan kode ini secara publik. Siapa pun yang memiliki kedua informasi tersebut dapat mencoba melacak aplikasi ini.', recoverLabel:'Pulihkan / Tambahkan Aplikasi', checkButton:'Cek', recoverHelp:'Jika tracking hilang karena pindah perangkat atau data browser terhapus, masukkan Application ID dan Recovery Code yang diberikan setelah submit.',
    fillAllFields:'Harap isi semua kolom!', gameIdNumbers:'Game ID hanya boleh berisi angka!', invalidNumbers:'Masukkan angka State dan Furnace Level yang valid dan tidak negatif.', furnaceRange:'Level Tungku harus antara 1 dan 10!', submitSuccess:'Aplikasi transfer berhasil dikirim!', submitError:'Gagal mengirim', unauthorized:'Tindakan tidak diizinkan!', confirmStatus:'Yakin ingin {action} aplikasi transfer pemain ini?', quotaReached:'Tidak dapat menerima! Batas kuota ({max}) sudah tercapai.', applicationStatusSuccess:'Aplikasi berhasil {status}!', statusUpdateFailed:'Gagal memperbarui status', notificationsBlocked:'Notifikasi browser diblokir. Anda dapat mengaktifkannya dari pengaturan browser.', notificationsEnabled:'Notifikasi browser berhasil diaktifkan.', notificationTracked:'🔔 Notifikasi untuk Aplikasi #{id} diaktifkan', trackingInApp:'🔔 Aplikasi #{id} sedang dilacak melalui notifikasi dalam halaman.', invalidApplicationId:'Masukkan Application ID yang valid.', invalidRecoveryCode:'Masukkan Recovery Code 8 karakter.', recoveryFailed:'Application ID atau Recovery Code salah.', trackingRestored:'Aplikasi #{id} berhasil dipulihkan untuk tracking di perangkat ini.', furnaceTouchRequired:'Atur Level Tungku dengan menggeser slider terlebih dahulu!',
    statePlaceholder:'contoh 3475', nicknamePlaceholder:'Masukkan nickname', gameIdPlaceholder:'Masukkan Game ID', alliancePlaceholder:'contoh ARX/CAT/IDN/VNX/ZXC', yourPower:'Power Anda', strongestHeroPower:'Power Hero Terkuat', totalHeroPowerPlaceholder:'Total Hero Power', referrerPlaceholder:'Siapa yang mengundang Anda? (opsional)', stateInfoPlaceholder:'Tulis aturan, persyaratan, atau profil state di sini...', adminNotePlaceholder:'Tambahkan catatan pribadi untuk pendaftar ini...', usernamePlaceholder:'Username', passwordPlaceholder:'Password', adminPasswordPlaceholder:'Password admin', applicationIdPlaceholder:'Application ID', recoveryCodePlaceholder:'Recovery Code'
  },
  it: {
    statusAccepted:'Accettato', statusRejected:'Rifiutato', statusWaiting:'In attesa', statusUpdated:'Aggiornato', detailPrefix:'Dettaglio', statePrefix:'Stato', maxSlotsUpdated:'Slot massimi aggiornati a {max}', nativeUpdateTitle:'Aggiornamento Domanda di Trasferimento', nativeUpdateBody:'La domanda #{id} ora è {status}.', nativeAcceptedTitle:'Domanda Accettata 🎉', nativeAcceptedBody:'{nickname} è stato accettato! Benvenuto nello stato.', nativeRejectedTitle:'Domanda Rifiutata', nativeRejectedBody:'{nickname} è stato rifiutato. Controlla il portale per i dettagli.', yourApplication:'La tua domanda', specialNotesSaved:'Note speciali salvate sul server!', specialNotesSaveFailed:'Errore nel salvataggio delle note speciali', stateInfoSaved:'Informazioni del profilo dello stato aggiornate in tempo reale!', stateInfoSaveFailed:'Impossibile salvare le informazioni dello stato', infoFieldsRequired:'Tutti i campi informativi devono essere compilati!', infoSaved:'Informazioni salvate sul server 3475', infoSaveFailed:'Il database non è riuscito a salvare le informazioni', invalidSlots:'Numero di slot non valido!', maxSlotsUpdateFailed:'Impossibile aggiornare gli slot massimi sul server', adminNoteSaved:'Nota amministrativa salvata con successo!', adminNoteSaveFailed:'Errore nel salvataggio della nota', recordDeleted:'Record eliminato con successo.', deleteFailed:'Eliminazione fallita', adminPasswordRequired:'Inserisci la password amministratore!', resetVerificationFailed:'Reset annullato. Il controllo di sicurezza non è riuscito.', confirmDelete:'Eliminare {name} definitivamente?\\n\\nQuesta azione non può essere annullata.', confirmReset:'⚠️ ATTENZIONE\\n\\nStai per eliminare definitivamente {count} domande di trasferimento.\\n\\nQuesta azione non può essere annullata.', verifying:'Verifica in corso...', allRecordsCleared:'Tutti i record di trasferimento sono stati cancellati!', resetFailed:'Reset fallito', acceptVerb:'accettare', rejectVerb:'rifiutare', loginFieldsRequired:'Inserisci sia il nome utente che la password!', presidentOnly:'Questa pagina è riservata solo all\'account Presidente.', signingIn:'Accesso in corso...', loginFailed:'Accesso fallito: nome utente o password errati', welcomePresident:'Bentornato, Presidente!', presidentLogout:'Logout Presidente', noDataExport:'Nessun dato da esportare', noTrackedApplications:'Nessuna domanda tracciata su questo dispositivo. Invia il modulo con "Ricevi Notifica?" selezionato, oppure recupera una domanda qui sopra.', loadingStatus:'Caricamento stato…', recordNotFound:'Record non trovato',
    logout:'Logout', presidentLoginShort:'Accesso Presidente', noApplications:'Nessuna domanda trovata', accept:'Accetta', reject:'Rifiuta', delete:'Elimina', details:'Dettagli', copyId:'Copia ID', pageTitle:'Registrazione Trasferimento Giocatore', portalTitle:'3475 - Portale Trasferimenti', portalSubtitle:'Invia i tuoi dati per immigrare nello stato',
    presidentManager:'Presidente/Gestore Stato:', alliance:'Alleanza:', gameIdShort:'ID:', save:'💾 Salva', specialNotes:'📝 Note Speciali', presidentMode:'● Modalità Presidente',
    transferForm:'Modulo di Trasferimento', transferSubtitle:'Inserisci i tuoi dati di trasferimento una sola volta. Puoi controllare lo stato qui sotto in tempo reale.', aboutState:'Il Nostro Stato', aboutStateTitle:'ℹ️ Il Nostro Stato', myApplicationStatus:'🔔 Stato della Mia Domanda',
    total:'Totale', accepted:'Accettati', left:'Rimanenti', registrationClosed:'⚠️ REGISTRAZIONI CHIUSE', quotaFull:'La quota di accettazione è attualmente piena.',
    transferFromState:'Trasferimento Dallo Stato', fromState:'Dallo Stato', nickname:'Nickname', gameId:'ID Gioco', desiredAlliance:'Alleanza Desiderata', furnaceLevel:'Livello Fornace', power:'Potenza', heroPower:'Potenza Eroe', totalHeroPower:'Potenza Eroe Totale', referrerOptional:'Referente (Facoltativo)', referrer:'Referente',
    getNotification:'🔔 Ricevi Notifica?', trackLive:'Traccia lo stato di questa domanda in tempo reale su questo dispositivo', submitApplication:'Invia Domanda', submitHint:'La tua domanda apparirà nell\'elenco subito dopo l\'invio.', viewApplicants:'Visualizza Candidati',
    applicantsList:'Elenco Candidati', realtimeStatus:'Stato domanda in tempo reale', resetPhase:'⚠️ Fase di Reset', exportCsv:'⇩ Esporta CSV', view:'Visualizza', action:'Azione', from:'Da', status:'Stato', playerDetail:'Dettaglio Giocatore', adminNotes:'Note Amministratore:', saveNote:'💾 Salva Nota',
    saveStateInfo:'💾 Salva Info Stato', adminSpecialNotes:'📝 Note Speciali Amministratore', specialNotesOnly:'Solo il Presidente/Gestore Stato può vedere e modificare questo campo.', saveSpecialNotes:'💾 Salva Note Speciali', presidentLogin:'👑 Accesso Presidente', username:'Nome utente', password:'Password', login:'🔐 Accedi', confirmPhaseReset:'⚠️ Conferma Reset Fase', resetWarning:'Questa azione eliminerà definitivamente TUTTI i record di trasferimento. Inserisci la password amministratore per confermare.', adminPassword:'Password Amministratore', deleteAllRecords:'⚠️ Elimina Tutti i Record',
    recoveryTitle:'🔐 Salva il Tuo Codice di Recupero', recoveryIntro:'Conserva questi due valori in modo sicuro. Sono necessari per recuperare le notifiche su un altro dispositivo o dopo aver cancellato i dati del browser.', applicationIdLabel:'ID Domanda', recoveryCodeLabel:'Codice di Recupero', copyRecovery:'📋 Copia Codice di Recupero', recoveryWarning:'Non condividere questo codice pubblicamente. Chiunque abbia entrambi i valori potrebbe essere in grado di tracciare questa domanda.', recoverLabel:'Recupera / Aggiungi Domanda', checkButton:'Verifica', recoverHelp:'Hai perso il tracciamento su un nuovo dispositivo o dopo aver cancellato i dati del browser? Inserisci l\'ID Domanda e il Codice di Recupero salvati dopo l\'invio.',
    fillAllFields:'Compila tutti i campi!', gameIdNumbers:'L\'ID Gioco deve contenere solo numeri!', invalidNumbers:'Inserisci un numero valido e non negativo per Stato e Livello Fornace!', furnaceRange:'Il Livello Fornace deve essere compreso tra 1 e 10!', submitSuccess:'Domanda di trasferimento inviata con successo!', submitError:'Errore durante l\'invio', unauthorized:'Azione non autorizzata!', confirmStatus:'Sei sicuro di voler {action} questa domanda di trasferimento del giocatore?', quotaReached:'Impossibile accettare! Il limite della quota ({max}) è stato raggiunto.', applicationStatusSuccess:'Domanda {status} con successo!', statusUpdateFailed:'Impossibile aggiornare lo stato', notificationsBlocked:'Le notifiche del browser sono bloccate. Puoi abilitarle nelle impostazioni del browser.', notificationsEnabled:'Notifiche del browser abilitate.', notificationTracked:'🔔 Notifiche abilitate per la Domanda #{id}', trackingInApp:'🔔 La Domanda #{id} viene tracciata con avvisi in-app.', invalidApplicationId:'Inserisci un ID Domanda numerico valido.', invalidRecoveryCode:'Inserisci il Codice di Recupero di 8 caratteri.', recoveryFailed:'ID Domanda o Codice di Recupero non corretti.', trackingRestored:'La Domanda #{id} è ora tracciata su questo dispositivo.', furnaceTouchRequired:'Imposta prima il Livello Fornace trascinando il cursore!',
    statePlaceholder:'es. 3475', nicknamePlaceholder:'Inserisci nickname', gameIdPlaceholder:'Inserisci ID Gioco', alliancePlaceholder:'es. ARX/CAT/IDN/VNX/ZXC', yourPower:'La Tua Potenza', strongestHeroPower:'Potenza Eroe più Forte', totalHeroPowerPlaceholder:'Potenza Eroe Totale', referrerPlaceholder:'Chi ti ha invitato? (facoltativo)', stateInfoPlaceholder:'Scrivi qui le regole, i requisiti o il profilo dello stato...', adminNotePlaceholder:'Aggiungi una nota privata per questo candidato...', usernamePlaceholder:'Nome utente', passwordPlaceholder:'Password', adminPasswordPlaceholder:'Password amministratore', applicationIdPlaceholder:'ID Domanda', recoveryCodePlaceholder:'Codice di Recupero'
  },
  tl: {
    statusAccepted:'Tinanggap', statusRejected:'Tinanggihan', statusWaiting:'Naghihintay', statusUpdated:'Na-update', detailPrefix:'Detalye', statePrefix:'State', maxSlotsUpdated:'Na-update ang maximum na slots sa {max}', nativeUpdateTitle:'Update sa Transfer Application', nativeUpdateBody:'Ang Application #{id} ay {status} na ngayon.', nativeAcceptedTitle:'Tinanggap ang Application 🎉', nativeAcceptedBody:'Tinanggap na si {nickname}! Maligayang pagdating sa state.', nativeRejectedTitle:'Tinanggihan ang Application', nativeRejectedBody:'Tinanggihan si {nickname}. Tingnan ang portal para sa detalye.', yourApplication:'Ang iyong application', specialNotesSaved:'Na-save na ang Special Notes sa server!', specialNotesSaveFailed:'Nabigo ang pag-save ng special notes', stateInfoSaved:'Na-update na ang impormasyon ng state profile nang real-time!', stateInfoSaveFailed:'Nabigo ang pag-save ng impormasyon ng state', infoFieldsRequired:'Kailangang punan lahat ng impormasyon!', infoSaved:'Na-save ang impormasyon sa 3475 Server', infoSaveFailed:'Nabigo ang database sa pag-save ng impormasyon', invalidSlots:'Hindi valid na bilang ng slots!', maxSlotsUpdateFailed:'Nabigo ang pag-update ng max slots sa server', adminNoteSaved:'Matagumpay na na-save ang admin note!', adminNoteSaveFailed:'Error sa pag-save ng note', recordDeleted:'Matagumpay na naburang ang record.', deleteFailed:'Nabigo ang pagbura', adminPasswordRequired:'Pakilagay ang admin password!', resetVerificationFailed:'Nakansela ang reset. Nabigo ang security verification.', confirmDelete:'Burahin ng permanente si {name}?\\n\\nHindi na ito puwedeng bawiin.', confirmReset:'⚠️ BABALA\\n\\nBubura ka ng permanente ng {count} transfer application(s).\\n\\nHindi na ito puwedeng bawiin.', verifying:'Nagve-verify...', allRecordsCleared:'Nabura na ang lahat ng transfer records!', resetFailed:'Nabigo ang reset', acceptVerb:'tanggapin', rejectVerb:'tanggihan', loginFieldsRequired:'Pakilagay ang username at password!', presidentOnly:'Ang page na ito ay para lamang sa account ng President.', signingIn:'Nagla-log in...', loginFailed:'Nabigo ang pag-login: mali ang username o password', welcomePresident:'Maligayang pagbabalik, President!', presidentLogout:'Naka-logout ang President', noDataExport:'Walang data na ie-export', noTrackedApplications:'Wala pang tracked application sa device na ito. I-submit ang form na naka-check ang “Get Notification?”, o i-recover ang isang application sa itaas.', loadingStatus:'Nilo-load ang status…', recordNotFound:'Hindi nahanap ang record',
    logout:'Logout', presidentLoginShort:'Login ng President', noApplications:'Walang nahanap na application', accept:'Tanggapin', reject:'Tanggihan', delete:'Burahin', details:'Detalye', copyId:'Kopyahin ang ID', pageTitle:'Rehistrasyon ng Transfer ng Manlalaro', portalTitle:'3475 - Transfer Portal', portalSubtitle:'I-submit ang iyong data para lumipat ng state',
    presidentManager:'President/State Manager:', alliance:'Alliance:', gameIdShort:'ID:', save:'💾 I-save', specialNotes:'📝 Special Notes', presidentMode:'● President Mode',
    transferForm:'Transfer Form', transferSubtitle:'Ilagay ang iyong mga detalye ng transfer isang beses lang. Puwede mong tingnan ang status sa ibaba nang real-time.', aboutState:'Tungkol sa Aming State', aboutStateTitle:'ℹ️ Tungkol sa Aming State', myApplicationStatus:'🔔 Status ng Aking Application',
    total:'Kabuuan', accepted:'Tinanggap', left:'Natitira', registrationClosed:'⚠️ SARADO NA ANG REHISTRASYON', quotaFull:'Puno na ang kasalukuyang quota ng tinanggap.',
    transferFromState:'Transfer Mula sa State', fromState:'Mula sa State', nickname:'Nickname', gameId:'Game ID', desiredAlliance:'Gustong Alliance', furnaceLevel:'Furnace Level', power:'Power', heroPower:'Hero Power', totalHeroPower:'Total Hero Power', referrerOptional:'Referrer (Opsyonal)', referrer:'Referrer',
    getNotification:'🔔 Kumuha ng Notification?', trackLive:'I-track ang status ng application na ito nang real-time sa device na ito', submitApplication:'I-submit ang Application', submitHint:'Lalabas agad ang iyong application sa listahan pagkatapos i-submit.', viewApplicants:'Tingnan ang mga Aplikante',
    applicantsList:'Listahan ng mga Aplikante', realtimeStatus:'Real-time na status ng application', resetPhase:'⚠️ Reset Phase', exportCsv:'⇩ I-export bilang CSV', view:'Tingnan', action:'Aksyon', from:'Mula sa', status:'Status', playerDetail:'Detalye ng Manlalaro', adminNotes:'Admin Notes:', saveNote:'💾 I-save ang Note',
    saveStateInfo:'💾 I-save ang State Info', adminSpecialNotes:'📝 Admin Special Notes', specialNotesOnly:'Tanging ang President/State Manager lamang ang makakakita at makakapag-edit ng field na ito.', saveSpecialNotes:'💾 I-save ang Special Notes', presidentLogin:'👑 Login ng President', username:'Username', password:'Password', login:'🔐 Mag-login', confirmPhaseReset:'⚠️ Kumpirmahin ang Phase Reset', resetWarning:'Permanenteng mabubura nito ang LAHAT ng transfer records. Ilagay ang admin password para kumpirmahin.', adminPassword:'Admin Password', deleteAllRecords:'⚠️ Burahin ang Lahat ng Records',
    recoveryTitle:'🔐 I-save ang Iyong Recovery Code', recoveryIntro:'Ingatan nang mabuti ang dalawang value na ito. Kailangan ang mga ito para ma-recover ang notifications sa ibang device o pagkatapos malinis ang data ng browser.', applicationIdLabel:'Application ID', recoveryCodeLabel:'Recovery Code', copyRecovery:'📋 Kopyahin ang Recovery Code', recoveryWarning:'Huwag ibahagi ang code na ito nang publiko. Sinumang may hawak ng parehong value ay maaaring ma-track ang application na ito.', recoverLabel:'I-recover / Magdagdag ng Application', checkButton:'I-check', recoverHelp:'Nawala ang tracking sa bagong device o pagkatapos malinis ang data ng browser? Ilagay ang Application ID at Recovery Code na na-save pagkatapos mag-submit.',
    fillAllFields:'Pakipunan ang lahat ng field!', gameIdNumbers:'Dapat mga numero lamang ang laman ng Game ID!', invalidNumbers:'Pakilagay ng valid at hindi negatibong numero para sa State at Furnace Level!', furnaceRange:'Ang Furnace Level ay dapat nasa pagitan ng 1 at 10!', submitSuccess:'Matagumpay na naipadala ang transfer application!', submitError:'Error sa pag-submit', unauthorized:'Hindi awtorisadong aksyon!', confirmStatus:'Sigurado ka bang gusto mong {action} ang transfer application ng manlalarong ito?', quotaReached:'Hindi puwedeng tanggapin! Naabot na ang quota limit ({max}).', applicationStatusSuccess:'Matagumpay na {status} ang application!', statusUpdateFailed:'Nabigo ang pag-update ng status', notificationsBlocked:'Naka-block ang browser notifications. Puwede mo itong i-enable sa browser settings.', notificationsEnabled:'Na-enable na ang browser notifications.', notificationTracked:'🔔 Na-enable ang notifications para sa Application #{id}', trackingInApp:'🔔 Tine-track ang Application #{id} gamit ang in-app alerts.', invalidApplicationId:'Pakilagay ng valid na numerong Application ID.', invalidRecoveryCode:'Pakilagay ang 8-character na Recovery Code.', recoveryFailed:'Mali ang Application ID o Recovery Code.', trackingRestored:'Tine-track na ngayon ang Application #{id} sa device na ito.', furnaceTouchRequired:'Itakda muna ang Furnace Level sa pamamagitan ng pag-drag ng slider!',
    statePlaceholder:'hal. 3475', nicknamePlaceholder:'Ilagay ang nickname', gameIdPlaceholder:'Ilagay ang Game ID', alliancePlaceholder:'hal. ARX/CAT/IDN/VNX/ZXC', yourPower:'Iyong Power', strongestHeroPower:'Pinakamalakas na Hero Power', totalHeroPowerPlaceholder:'Total Hero Power', referrerPlaceholder:'Sino ang nag-refer sa iyo? (opsyonal)', stateInfoPlaceholder:'Isulat dito ang mga panuntunan, requirements, o profile ng state...', adminNotePlaceholder:'Magdagdag ng pribadong note para sa aplikanteng ito...', usernamePlaceholder:'Username', passwordPlaceholder:'Password', adminPasswordPlaceholder:'Admin password', applicationIdPlaceholder:'Application ID', recoveryCodePlaceholder:'Recovery Code'
  }
};

function currentLanguage(){ return localStorage.getItem(LANG_KEY) || 'en'; }
function t(key, vars={}){
  const lang=currentLanguage();
  let text=(translations[lang]&&translations[lang][key])||translations.en[key]||key;
  return String(text).replace(/\{(\w+)\}/g,(_,k)=>vars[k]===undefined?`{${k}}`:String(vars[k]));
}
function applyLanguage(lang){
  if(!translations[lang]) lang='en';
  localStorage.setItem(LANG_KEY,lang);
  document.documentElement.lang=lang==='cn'?'zh-CN':lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{ el.textContent=t(el.dataset.i18n); });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{ el.placeholder=t(el.dataset.i18nPlaceholder); });
  const title=document.querySelector('title[data-i18n]'); if(title) title.textContent=t(title.dataset.i18n);
  document.querySelectorAll('.language-option').forEach(btn=>{ const active=btn.dataset.lang===lang; btn.classList.toggle('active',active); btn.setAttribute('aria-pressed',active?'true':'false'); });
  const adminBtn=document.getElementById('admin-btn');
  if(adminBtn && typeof isAdmin !== 'undefined') adminBtn.innerText = isAdmin ? `${t('logout')} (${String(currentStaffUsername || '').toUpperCase()})` : '👑';
  if(typeof renderTable==='function') renderTable();
}
function translateDynamicMessage(message){
  if(!message || typeof message!=='string') return message;
  const lang=currentLanguage(); if(lang==='en') return message;
  const exact={
    'Transfer application sent successfully!':'submitSuccess',
    'Please fill all input fields!':'fillAllFields',
    'Game ID must contain numbers only!':'gameIdNumbers',
    'Furnace Level must be between 1 and 10!':'furnaceRange',
    'Unauthorized action!':'unauthorized',
    'Browser notifications are blocked. You can enable them in browser settings.':'notificationsBlocked'
  };
  return exact[message]?t(exact[message]):message;
}

document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('.language-option').forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));
  applyLanguage(currentLanguage());
});
